version: "3.8"
services:
  httpapi:
    build: ./httpapi
    depends_on:
      - storage
    environment:
      TARANTOOL_HOST: storage
      ACCESS_LOG: ""
      APP_MODULE: service.api:app
      API_URL: http://localhost   # Used in benchmark.py
    ports:
    - "8080:80"
  storage:
    image: tarantool/tarantool:2.6.0
    volumes:
    - urlstorage:/var/lib/tarantool
    - ./storage/scripts:/opt/tarantool
    ports:
    - "3301:3301"
    command: ["tarantool", "url_storage.lua"]

volumes:
  urlstorage: